/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Color;
import vistas.FrmProductos;
/**
 *
 * @author micro
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        
      
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        MenuLateral = new javax.swing.JPanel();
        TitleOpciones = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnOperadores = new javax.swing.JPanel();
        OperadoresTxt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCategorias = new javax.swing.JPanel();
        CategoriasTxt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnProductos = new javax.swing.JPanel();
        ProductosTxt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnMarcas = new javax.swing.JPanel();
        MarcaTxt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PanelDescripcion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuLateral.setBackground(new java.awt.Color(125, 67, 120));
        MenuLateral.setPreferredSize(new java.awt.Dimension(220, 620));
        MenuLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleOpciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TitleOpciones.setForeground(new java.awt.Color(255, 255, 255));
        TitleOpciones.setText("Opciones");
        MenuLateral.add(TitleOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 34, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        MenuLateral.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 71, 144, 10));

        btnOperadores.setBackground(new java.awt.Color(190, 90, 131));

        OperadoresTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        OperadoresTxt.setForeground(new java.awt.Color(255, 204, 153));
        OperadoresTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        OperadoresTxt.setText("Operadores");
        OperadoresTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OperadoresTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OperadoresTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OperadoresTxtMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\micro\\Downloads\\JavaAppClient\\src\\main\\java\\imagenes\\stay-at-home.png")); // NOI18N

        javax.swing.GroupLayout btnOperadoresLayout = new javax.swing.GroupLayout(btnOperadores);
        btnOperadores.setLayout(btnOperadoresLayout);
        btnOperadoresLayout.setHorizontalGroup(
            btnOperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnOperadoresLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OperadoresTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        btnOperadoresLayout.setVerticalGroup(
            btnOperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnOperadoresLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(btnOperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(OperadoresTxt))
                .addGap(10, 10, 10))
        );

        MenuLateral.add(btnOperadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 230, 60));

        btnCategorias.setBackground(new java.awt.Color(190, 90, 131));

        CategoriasTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CategoriasTxt.setForeground(new java.awt.Color(255, 204, 153));
        CategoriasTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CategoriasTxt.setText("Categorias");
        CategoriasTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoriasTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CategoriasTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CategoriasTxtMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\micro\\Downloads\\JavaAppClient\\src\\main\\java\\imagenes\\aplicacion.png")); // NOI18N

        javax.swing.GroupLayout btnCategoriasLayout = new javax.swing.GroupLayout(btnCategorias);
        btnCategorias.setLayout(btnCategoriasLayout);
        btnCategoriasLayout.setHorizontalGroup(
            btnCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCategoriasLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CategoriasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        btnCategoriasLayout.setVerticalGroup(
            btnCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCategoriasLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(btnCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(CategoriasTxt))
                .addGap(15, 15, 15))
        );

        MenuLateral.add(btnCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 230, 60));

        btnProductos.setBackground(new java.awt.Color(190, 90, 131));

        ProductosTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ProductosTxt.setForeground(new java.awt.Color(255, 204, 153));
        ProductosTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ProductosTxt.setText("Productos");
        ProductosTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductosTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProductosTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProductosTxtMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\micro\\Downloads\\JavaAppClient\\src\\main\\java\\imagenes\\caja.png")); // NOI18N

        javax.swing.GroupLayout btnProductosLayout = new javax.swing.GroupLayout(btnProductos);
        btnProductos.setLayout(btnProductosLayout);
        btnProductosLayout.setHorizontalGroup(
            btnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProductosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProductosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        btnProductosLayout.setVerticalGroup(
            btnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnProductosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(btnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProductosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        MenuLateral.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 230, 60));

        btnMarcas.setBackground(new java.awt.Color(190, 90, 131));

        MarcaTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MarcaTxt.setForeground(new java.awt.Color(255, 204, 153));
        MarcaTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MarcaTxt.setText("Marca productos");
        MarcaTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MarcaTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MarcaTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MarcaTxtMouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\micro\\Downloads\\JavaAppClient\\src\\main\\java\\imagenes\\etiqueta-de-precio.png")); // NOI18N

        javax.swing.GroupLayout btnMarcasLayout = new javax.swing.GroupLayout(btnMarcas);
        btnMarcas.setLayout(btnMarcasLayout);
        btnMarcasLayout.setHorizontalGroup(
            btnMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMarcasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MarcaTxt)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        btnMarcasLayout.setVerticalGroup(
            btnMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMarcasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(btnMarcasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MarcaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        MenuLateral.add(btnMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 230, 60));

        bg.add(MenuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 620));

        PanelDescripcion.setBackground(new java.awt.Color(125, 67, 120));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administración/Control/Inventario");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BIENVENIDO AL SISTEMA");

        javax.swing.GroupLayout PanelDescripcionLayout = new javax.swing.GroupLayout(PanelDescripcion);
        PanelDescripcion.setLayout(PanelDescripcionLayout);
        PanelDescripcionLayout.setHorizontalGroup(
            PanelDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDescripcionLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(PanelDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(502, Short.MAX_VALUE))
        );
        PanelDescripcionLayout.setVerticalGroup(
            PanelDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDescripcionLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        bg.add(PanelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 880, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\micro\\Downloads\\JavaAppClient\\src\\main\\java\\imagenes\\logoEmpresa.png")); // NOI18N
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\micro\\Downloads\\JavaAppClient\\src\\main\\java\\imagenes\\fondoMenuInicio.png")); // NOI18N
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 186, 870, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductosTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosTxtMouseClicked
        FrmProductos vista = new FrmProductos();
            vista.setVisible(true);
            dispose();
    }//GEN-LAST:event_ProductosTxtMouseClicked

    private void ProductosTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosTxtMouseEntered
        btnProductos.setBackground(new Color(125, 67, 120));
    }//GEN-LAST:event_ProductosTxtMouseEntered

    private void ProductosTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductosTxtMouseExited
        btnProductos.setBackground(new Color(190, 90, 131));
    }//GEN-LAST:event_ProductosTxtMouseExited

    private void MarcaTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MarcaTxtMouseClicked
        FrmMarcas vista = new FrmMarcas();
            vista.setVisible(true);
            dispose();
    }//GEN-LAST:event_MarcaTxtMouseClicked

    private void MarcaTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MarcaTxtMouseEntered
        btnMarcas.setBackground(new Color(125, 67, 120));
    }//GEN-LAST:event_MarcaTxtMouseEntered

    private void MarcaTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MarcaTxtMouseExited
         btnMarcas.setBackground(new Color(190, 90, 131));
    }//GEN-LAST:event_MarcaTxtMouseExited

    private void CategoriasTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriasTxtMouseClicked
        FrmCategorias vista = new FrmCategorias();
            vista.setVisible(true);
            dispose();
    }//GEN-LAST:event_CategoriasTxtMouseClicked

    private void CategoriasTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriasTxtMouseEntered
        btnCategorias.setBackground(new Color(125, 67, 120));
    }//GEN-LAST:event_CategoriasTxtMouseEntered

    private void CategoriasTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriasTxtMouseExited
        btnCategorias.setBackground(new Color(190, 90, 131));
    }//GEN-LAST:event_CategoriasTxtMouseExited

    private void OperadoresTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OperadoresTxtMouseClicked
        FrmOperadores vista = new FrmOperadores();
            vista.setVisible(true);
            dispose();
    }//GEN-LAST:event_OperadoresTxtMouseClicked

    private void OperadoresTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OperadoresTxtMouseEntered
        btnOperadores.setBackground(new Color(125, 67, 120));
    }//GEN-LAST:event_OperadoresTxtMouseEntered

    private void OperadoresTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OperadoresTxtMouseExited
       btnOperadores.setBackground(new Color(190, 90, 131));
    }//GEN-LAST:event_OperadoresTxtMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CategoriasTxt;
    private javax.swing.JLabel MarcaTxt;
    private javax.swing.JPanel MenuLateral;
    private javax.swing.JLabel OperadoresTxt;
    private javax.swing.JPanel PanelDescripcion;
    private javax.swing.JLabel ProductosTxt;
    private javax.swing.JLabel TitleOpciones;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnCategorias;
    private javax.swing.JPanel btnMarcas;
    private javax.swing.JPanel btnOperadores;
    private javax.swing.JPanel btnProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
